2014-08-19 14:30:32,069 INFO views 5561 -1273976000 test logging
2014-08-19 14:31:51,003 INFO tasks 5654 -1219176704 add task executed
2014-08-19 16:12:17,823 INFO tasks 5652 -1219176704 add task executed
2014-08-19 16:12:48,786 ERROR base 7410 -1274340544 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 343, in dispatch
    return super(Test, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 154, in get
    context = self.get_context_data(**kwargs)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 385, in get_context_data
    context['summ'] = res.get()
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 172, in get
    self._get_task_meta()  # update self._cache
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 328, in _get_task_meta
    meta = self.backend.get_task_meta(self.id)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 294, in get_task_meta
    meta = self._get_task_meta_for(task_id)
AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for'
2014-08-19 16:12:50,078 INFO tasks 5654 -1219176704 add task executed
2014-08-19 16:13:17,349 INFO tasks 5652 -1219176704 add task executed
2014-08-19 16:13:17,347 ERROR base 7449 -1274340544 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 343, in dispatch
    return super(Test, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 154, in get
    context = self.get_context_data(**kwargs)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 385, in get_context_data
    context['summ'] = res.get(timeout=1)
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 172, in get
    self._get_task_meta()  # update self._cache
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 328, in _get_task_meta
    meta = self.backend.get_task_meta(self.id)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 294, in get_task_meta
    meta = self._get_task_meta_for(task_id)
AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for'
2014-08-19 16:16:37,204 INFO tasks 5654 -1219176704 add task executed
2014-08-19 16:16:37,154 ERROR base 7529 -1273967808 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 343, in dispatch
    return super(Test, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 154, in get
    context = self.get_context_data(**kwargs)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 385, in get_context_data
    context['summ'] = res.get(timeout=1)
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 172, in get
    self._get_task_meta()  # update self._cache
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 328, in _get_task_meta
    meta = self.backend.get_task_meta(self.id)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 294, in get_task_meta
    meta = self._get_task_meta_for(task_id)
AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for'
2014-08-19 16:17:15,361 ERROR base 7555 -1274340544 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 343, in dispatch
    return super(Test, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 154, in get
    context = self.get_context_data(**kwargs)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 385, in get_context_data
    context['summ'] = res.get(timeout=1)
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 172, in get
    self._get_task_meta()  # update self._cache
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 328, in _get_task_meta
    meta = self.backend.get_task_meta(self.id)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 294, in get_task_meta
    meta = self._get_task_meta_for(task_id)
AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for'
2014-08-19 16:17:15,365 INFO tasks 7573 -1219045632 add task executed
2014-08-19 16:20:20,102 INFO tasks 7679 -1219000576 add task executed
2014-08-19 16:21:18,158 INFO tasks 7678 -1219000576 add task executed
2014-08-19 16:22:19,814 INFO tasks 7679 -1219000576 add task executed
2014-08-19 16:22:37,513 ERROR base 7769 -1294992576 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 343, in dispatch
    return super(Test, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 154, in get
    context = self.get_context_data(**kwargs)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 385, in get_context_data
    context['summ'] = res.get(timeout=1)
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 169, in get
    no_ack=no_ack,
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/amqp.py", line 157, in wait_for
    raise TimeoutError('The operation timed out.')
TimeoutError: The operation timed out.
2014-08-19 16:23:06,302 INFO tasks 7804 -1219041536 add task executed
2014-08-19 16:23:56,606 INFO tasks 7802 -1219041536 add task executed
2014-08-19 16:48:37,318 INFO tasks 7804 -1219041536 add task executed
2014-08-25 15:01:53,035 INFO tasks 6643 -1218971904 add task executed
2014-08-25 15:33:33,696 ERROR base 7611 -1273439424 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 343, in dispatch
    return super(Test, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 154, in get
    context = self.get_context_data(**kwargs)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 357, in get_context_data
    context['summ'] = "just string"
NameError: global name 'context' is not defined
2014-08-25 15:36:09,931 ERROR base 7807 -1314915520 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:36:19,801 ERROR base 7807 -1273615552 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:36:42,082 ERROR base 7807 -1273615552 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:32,002 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:40,814 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:41,478 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:41,646 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:41,839 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:42,012 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:42,166 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:42,322 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:42,487 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:42,661 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:42,838 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:42,998 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:39:46,791 ERROR base 7966 -1283720384 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-25 15:40:00,232 ERROR base 8034 -1283458240 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'int' object has no attribute 'get'
2014-08-25 15:40:10,431 ERROR base 8071 -1304429760 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-25 15:41:24,428 ERROR base 8120 -1304429760 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-25 15:41:26,965 ERROR base 8120 -1304429760 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-25 15:41:27,131 ERROR base 8120 -1304429760 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-25 15:41:27,307 ERROR base 8120 -1304429760 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-25 15:42:32,664 ERROR base 8120 -1335887040 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-25 15:43:54,239 ERROR base 8120 -1314915520 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-25 15:44:11,821 ERROR base 8120 -1273500864 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-27 14:51:06,762 ERROR base 8662 -1326449856 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-27 14:55:39,579 ERROR base 8662 -1326449856 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-27 14:56:06,289 ERROR base 8662 -1326449856 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-27 14:56:16,117 ERROR base 8662 -1284506816 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-27 14:56:31,846 ERROR base 8662 -1326449856 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'bool' object has no attribute 'get'
2014-08-27 14:58:37,625 ERROR base 9015 -1296041152 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-27 15:04:52,424 ERROR base 9129 -1273910464 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-27 15:10:15,725 ERROR base 9198 -1326449856 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-27 15:27:04,219 ERROR base 9333 -1305478336 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-27 15:29:27,102 ERROR base 9845 -1273615552 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 346, in dispatch
    return super(Test, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 342, in post
    return self.render_to_response(self.get_context_data( request, **kwargs), **kwargs)
TypeError: get_context_data() takes exactly 1 argument (2 given)
2014-08-27 15:30:18,681 ERROR base 9845 -1304429760 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 346, in dispatch
    return super(Test, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 342, in post
    return self.render_to_response(self.get_context_data( request, **kwargs), **kwargs)
TypeError: get_context_data() takes exactly 1 argument (2 given)
2014-08-27 15:30:30,172 ERROR base 9904 -1294992576 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-27 15:30:48,314 ERROR base 9939 -1294992576 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-27 15:31:18,148 ERROR base 9980 -1276118208 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-27 15:32:28,498 ERROR base 10043 -1273910464 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/clickjacking.py", line 30, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
2014-08-27 16:04:41,685 ERROR base 10870 -1274041536 Internal Server Error: /task_status/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 408, in dispatch
    return super(TaskStatus, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 154, in get
    context = self.get_context_data(**kwargs)
  File "/home/mikhail/EclipseWorkspace/oncoFinder2/core/views.py", line 413, in get_context_data
    context = super(Test, self).get_context_data(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
2014-08-27 16:34:47,268 INFO tasks 11767 -1219123456 add task executed
2014-08-27 16:36:25,315 INFO tasks 11765 -1219123456 add task executed
2014-08-27 16:37:00,210 INFO tasks 11767 -1219123456 add task executed
2014-08-27 16:39:16,723 INFO tasks 11765 -1219123456 add task executed
2014-08-27 16:40:09,165 INFO tasks 11767 -1219123456 add task executed
2014-08-27 16:43:42,258 INFO tasks 11765 -1219123456 add task executed
2014-08-27 16:45:56,859 INFO tasks 11767 -1219123456 add task executed
2014-08-27 16:47:47,323 INFO tasks 11765 -1219123456 add task executed
2014-08-27 16:48:52,121 INFO tasks 11767 -1219123456 add task executed
2014-08-27 16:52:51,795 INFO tasks 11765 -1219123456 add task executed
2014-08-27 17:23:17,783 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:23:17,786 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:23:18,125 INFO tasks 9161 -1219250432 add task executed
2014-08-27 17:23:18,349 INFO tasks 9163 -1219250432 add task executed
2014-08-27 17:23:47,972 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:23:48,316 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:23:48,475 INFO tasks 9163 -1219250432 add task executed
2014-08-27 17:24:18,143 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:24:18,436 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:24:48,310 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:24:48,542 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:25:18,422 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:25:18,677 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:25:48,553 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:25:48,820 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:26:18,675 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:26:18,957 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:26:48,827 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:26:49,066 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:27:18,959 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:27:19,188 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:27:49,078 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:27:49,311 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:28:19,202 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:28:19,446 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:28:49,400 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:28:49,539 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:29:19,524 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:29:19,674 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:29:49,721 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:29:49,821 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:30:19,851 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:30:19,930 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:30:49,979 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:30:50,079 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:31:20,112 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:31:20,198 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:31:50,241 INFO tasks 9162 -1219250432 add task executed
2014-08-27 17:31:50,318 INFO tasks 9164 -1219250432 add task executed
2014-08-27 17:32:35,309 INFO tasks 9312 -1219381504 add task executed
2014-08-27 17:32:35,325 INFO tasks 9313 -1219381504 add task executed
2014-08-27 17:32:35,332 INFO tasks 9314 -1219381504 add task executed
2014-08-27 17:32:35,335 INFO tasks 9311 -1219381504 add task executed
2014-08-27 17:33:05,499 INFO tasks 9313 -1219381504 add task executed
2014-08-27 17:33:05,526 INFO tasks 9312 -1219381504 add task executed
2014-08-27 17:33:35,675 INFO tasks 9313 -1219381504 add task executed
2014-08-27 17:33:35,700 INFO tasks 9312 -1219381504 add task executed
2014-08-27 17:34:05,851 INFO tasks 9313 -1219381504 add task executed
2014-08-27 17:34:05,876 INFO tasks 9312 -1219381504 add task executed
2014-08-27 17:34:36,033 INFO tasks 9313 -1219381504 add task executed
2014-08-27 17:34:36,073 INFO tasks 9312 -1219381504 add task executed
2014-08-27 17:35:06,234 INFO tasks 9313 -1219381504 add task executed
2014-08-27 17:35:06,260 INFO tasks 9312 -1219381504 add task executed
2014-08-27 17:35:36,414 INFO tasks 9313 -1219381504 add task executed
2014-08-27 17:35:36,459 INFO tasks 9312 -1219381504 add task executed
2014-08-27 17:36:06,546 INFO tasks 9313 -1219381504 add task executed
2014-08-27 17:39:07,092 INFO tasks 9412 -1219102976 add task executed
2014-08-27 17:40:30,154 INFO tasks 9411 -1219102976 add task executed
2014-08-27 17:47:18,688 INFO tasks 9412 -1219102976 add task executed
2014-08-28 15:02:07,545 INFO tasks 6186 -1219008768 add task executed
2014-08-28 15:02:47,054 INFO tasks 6185 -1219008768 add task executed
2014-08-28 15:04:43,834 INFO tasks 6186 -1219008768 add task executed
2014-08-28 15:07:53,129 INFO tasks 6185 -1219008768 add task executed
2014-08-28 15:08:16,621 INFO tasks 6186 -1219008768 add task executed
2014-08-28 15:09:36,111 INFO tasks 6185 -1219008768 add task executed
2014-08-28 15:09:37,330 INFO tasks 6186 -1219008768 add task executed
2014-09-03 15:39:28,501 ERROR base 15126 -1273914560 Internal Server Error: /ws/about/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: website/about.html
